language: cpp

matrix:
  include:
  - os: linux
    dist: bionic
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - gcc-8
        - g++-8
    env:
    - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

# - os: osx
#   osx_image: xcode10.1

before_install:
- bash ${TRAVIS_BUILD_DIR}/.travis/before_install.sh

install:
- bash ${TRAVIS_BUILD_DIR}/.travis/install.sh

script:
- bash ${TRAVIS_BUILD_DIR}/.travis/script.sh

after_failure:
- bash ${TRAVIS_BUILD_DIR}/.travis/after_failure.sh

after_success:
- bash ${TRAVIS_BUILD_DIR}/.travis/after_success.sh
